run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/kubeace/azure-cost-cli

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
