// Package azure wraps the Azure Cost Management query API and Azure Monitor
// metrics API. It deliberately uses raw HTTP rather than the autogenerated SDK
// clients because Cost Management's query response shape (rows + columns) is
// awkward to model in the generated types, and Monitor's metric splitting
// requires URL params the SDK does not expose cleanly.
package azure

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
)

const (
	armScope        = "https://management.azure.com/.default"
	httpTimeout     = 90 * time.Second
	maxAttempts     = 8
	initialBackoff  = 5 * time.Second
	maxBackoff      = 2 * time.Minute
	defaultRPS      = 5
	truncateErrChar = 500
)

// Client is a throttled, retrying HTTP client for ARM endpoints. Safe for
// concurrent use; the throttle is a shared channel.
type Client struct {
	cred     azcore.TokenCredential
	http     *http.Client
	throttle <-chan time.Time
}

// AuthMode controls which credential source the client uses. "auto" lets
// DefaultAzureCredential pick (env > workload identity > MSI > CLI). "cli"
// forces AzureCLICredential, useful when AZURE_* env vars are loaded but the
// EA enrollment blocks SP cost reads. "sp" forces ClientSecret/Env credentials
// — fails fast if AZURE_CLIENT_ID isn't set, rather than silently falling back.
type AuthMode string

const (
	AuthAuto AuthMode = "auto"
	AuthCLI  AuthMode = "cli"
	AuthSP   AuthMode = "sp"
)

// NewClient creates a Client. reqPerSec caps outbound ARM requests across all
// goroutines. tenantID is optional; when non-empty it disambiguates az login
// sessions that hold multiple tenants. mode chooses the credential chain.
func NewClient(reqPerSec int, tenantID string, mode AuthMode) (*Client, error) {
	cred, err := newCredential(tenantID, mode)
	if err != nil {
		return nil, err
	}
	if reqPerSec <= 0 {
		reqPerSec = defaultRPS
	}
	return &Client{
		cred:     cred,
		http:     &http.Client{Timeout: httpTimeout},
		throttle: time.Tick(time.Second / time.Duration(reqPerSec)),
	}, nil
}

func newCredential(tenantID string, mode AuthMode) (azcore.TokenCredential, error) {
	switch mode {
	case AuthCLI:
		var opts *azidentity.AzureCLICredentialOptions
		if tenantID != "" {
			opts = &azidentity.AzureCLICredentialOptions{TenantID: tenantID}
		}
		c, err := azidentity.NewAzureCLICredential(opts)
		if err != nil {
			return nil, fmt.Errorf("cli credential: %w", err)
		}
		return c, nil
	case AuthSP:
		// Honor --tenant override: when set, mint a ClientSecretCredential
		// against that tenant instead of EnvironmentCredential (which reads
		// AZURE_TENANT_ID and ignores the flag). This is essential for cross-
		// tenant SP queries where AZURE_TENANT_ID points at the SP's home
		// tenant but the subscription lives elsewhere.
		clientID := os.Getenv("AZURE_CLIENT_ID")
		clientSecret := os.Getenv("AZURE_CLIENT_SECRET")
		if clientID == "" || clientSecret == "" {
			return nil, fmt.Errorf("--auth sp requires AZURE_CLIENT_ID + AZURE_CLIENT_SECRET in env")
		}
		t := tenantID
		if t == "" {
			t = os.Getenv("AZURE_TENANT_ID")
		}
		if t == "" {
			return nil, fmt.Errorf("--auth sp requires --tenant or AZURE_TENANT_ID")
		}
		c, err := azidentity.NewClientSecretCredential(t, clientID, clientSecret, nil)
		if err != nil {
			return nil, fmt.Errorf("sp credential: %w", err)
		}
		return c, nil
	case AuthAuto, "":
		var opts *azidentity.DefaultAzureCredentialOptions
		if tenantID != "" {
			opts = &azidentity.DefaultAzureCredentialOptions{TenantID: tenantID}
		}
		c, err := azidentity.NewDefaultAzureCredential(opts)
		if err != nil {
			return nil, fmt.Errorf("default credential: %w", err)
		}
		return c, nil
	default:
		return nil, fmt.Errorf("unknown auth mode %q (want auto|cli|sp)", mode)
	}
}

// NewClientWithCred is for tests that need to inject a fake credential and/or
// custom RoundTripper without touching real Azure auth.
func NewClientWithCred(cred azcore.TokenCredential, rt http.RoundTripper, reqPerSec int) *Client {
	if reqPerSec <= 0 {
		reqPerSec = defaultRPS
	}
	return &Client{
		cred:     cred,
		http:     &http.Client{Timeout: httpTimeout, Transport: rt},
		throttle: time.Tick(time.Second / time.Duration(reqPerSec)),
	}
}

func (c *Client) token(ctx context.Context) (string, error) {
	tk, err := c.cred.GetToken(ctx, policy.TokenRequestOptions{Scopes: []string{armScope}})
	if err != nil {
		return "", fmt.Errorf("get token: %w", err)
	}
	return tk.Token, nil
}

// Post issues a POST against url with body marshalled to JSON, decoding the
// response into out. Retries 429/503 with exponential backoff.
func (c *Client) Post(ctx context.Context, url string, body, out any) error {
	payload, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("marshal body: %w", err)
	}
	return c.do(ctx, http.MethodPost, url, payload, out)
}

// Get issues a GET; same retry semantics as Post.
func (c *Client) Get(ctx context.Context, url string, out any) error {
	return c.do(ctx, http.MethodGet, url, nil, out)
}

func (c *Client) do(ctx context.Context, method, url string, payload []byte, out any) error {
	backoff := initialBackoff
	for attempt := 0; attempt < maxAttempts; attempt++ {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-c.throttle:
		}

		tk, err := c.token(ctx)
		if err != nil {
			return err
		}

		var bodyR io.Reader
		if payload != nil {
			bodyR = bytes.NewReader(payload)
		}
		req, err := http.NewRequestWithContext(ctx, method, url, bodyR)
		if err != nil {
			return fmt.Errorf("new request: %w", err)
		}
		req.Header.Set("Authorization", "Bearer "+tk)
		if payload != nil {
			req.Header.Set("Content-Type", "application/json")
		}

		resp, err := c.http.Do(req)
		if err != nil {
			return fmt.Errorf("%s %s: %w", method, url, err)
		}
		respBody, _ := io.ReadAll(resp.Body)
		resp.Body.Close()

		switch resp.StatusCode {
		case http.StatusOK, http.StatusCreated, http.StatusAccepted:
			if out == nil {
				return nil
			}
			if err := json.Unmarshal(respBody, out); err != nil {
				return fmt.Errorf("decode %s response: %w", url, err)
			}
			return nil
		case http.StatusTooManyRequests, http.StatusServiceUnavailable:
			wait := backoffFromRetryAfter(resp.Header.Get("Retry-After"), backoff)
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-time.After(wait):
			}
			backoff *= 2
			if backoff > maxBackoff {
				backoff = maxBackoff
			}
		default:
			return fmt.Errorf("%s %s: status %d: %s", method, url, resp.StatusCode, truncate(string(respBody), truncateErrChar))
		}
	}
	return fmt.Errorf("%s %s: gave up after %d attempts", method, url, maxAttempts)
}

// backoffFromRetryAfter parses delta-seconds or HTTP-date Retry-After headers,
// falling back to def when missing or unparseable.
func backoffFromRetryAfter(h string, def time.Duration) time.Duration {
	if h == "" {
		return def
	}
	if secs, err := strconv.Atoi(h); err == nil && secs > 0 {
		return time.Duration(secs) * time.Second
	}
	if t, err := http.ParseTime(h); err == nil {
		if d := time.Until(t); d > 0 {
			return d
		}
	}
	return def
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
